In [1]:
import dgl
import lightning.pytorch as pl
import pandas as pd
import torch
from sportsml.mongo import client
from sportsml.nfl.data.features import GRAPH_FEATURES
from sportsml.nfl.data.nodes import team_abr_map
from sportsml.layers.gnn.encoder.heterogcn import HeteroGCNEncoder
from sportsml.layers.gnn.predictor.heteronn import HeteroNNPredictor
from sportsml.models.gnn import GraphModel
from sportsml.utils.datamodule import HeteroGraphDataModule
from sportsml.utils.heterograph import heterograph_encoder

DGL backend not selected or invalid.  Assuming PyTorch for now.

Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)

/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)

In [2]:
games = pd.DataFrame(client.nfl.games.find({})).dropna(subset=GRAPH_FEATURES)

In [3]:
games['won'] = games['score'] > games['opp_score']
games['home'] = games['home'].astype(bool)
games['y'] = games['score'] - games['opp_score']

In [4]:
dm = HeteroGraphDataModule(
    games=games,
    feature_columns=GRAPH_FEATURES,
    target_columns=['y'],
    win_column='won',
    home_column='home',
    season_column='season',
    date_column='week',
    team_column='team',
    num_nodes=32
)

In [5]:
model = GraphModel(
    encoder=HeteroGCNEncoder(54, 300),
    predictor=HeteroNNPredictor(300, 300, 1),
)

/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/parsing.py:197: UserWarning: Attribute 'encoder' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['encoder'])`.
  rank_zero_warn(
/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/parsing.py:197: UserWarning: Attribute 'predictor' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['predictor'])`.
  rank_zero_warn(

In [6]:
trainer = pl.Trainer(
    max_epochs=-1,
    logger=pl.loggers.CSVLogger(save_dir="model", name="model"),
    callbacks=[
        pl.callbacks.ModelCheckpoint(monitor="val_rmse"),
        pl.callbacks.early_stopping.EarlyStopping(monitor="val_rmse", patience=10)
    ]
)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

In [7]:
trainer.fit(model, dm)

  | Name            | Type                | Params
--------------------------------------------------------
0 | encoder         | HeteroGCNEncoder    | 578 K
1 | predictor       | HeteroNNPredictor   | 367 K
2 | rmse            | MeanSquaredError    | 0
3 | mae             | MeanAbsoluteError   | 0
4 | accuracy_score  | MulticlassAccuracy  | 0
5 | precision_score | MulticlassPrecision | 0
6 | recall_score    | MulticlassRecall    | 0
--------------------------------------------------------
945 K     Trainable params
0         Non-trainable params
945 K     Total params
3.782     Total estimated model params size (MB)

/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py:281: PossibleUserWarning: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(

Epoch 1: 100%|██████████| 6/6 [00:07<00:00,  1.25s/it, v_num=0, train_loss=217.0, val_rmse=15.10]

/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:152: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)

Epoch 16: 100%|██████████| 6/6 [00:27<00:00,  4.60s/it, v_num=0, train_loss=87.60, val_rmse=17.50]

In [8]:
s2022 = games[games['season'] == 2022]
s2023 = games[games['season'] == 2023]

In [9]:
g = heterograph_encoder(
    src=s2023['src'].values,
    dst=s2023['target'].values,
    feat=s2023[GRAPH_FEATURES].values,
    won_mask=s2023['won'].values,
    num_nodes=32
)

In [10]:
preds = model.predict(g)

In [11]:
hu, hv = preds.edges(etype="home")

In [17]:
df = pd.DataFrame()
df['team'] = hu
df['opp'] = hv
df['f'] = preds.edges["away"].data["pred"].detach().numpy()

In [18]:
df = df.pivot_table(index="team", columns="opp", values="f")

In [19]:
df = df.rename(index=team_abr_map, columns=team_abr_map)

In [20]:
df = df.reindex(df.mean(axis=1).sort_values(ascending=False).index)
df = df.reindex(df.mean(axis=1).sort_values(ascending=False).index, axis=1)

In [21]:
df

team,NYG,NO,CIN,PIT,TB,DEN,WAS,LV,CHI,LAC,...,HOU,JAX,LA,NE,KC,TEN,DAL,MIN,BAL,BUF
team,,,,,,,,,,,,,,,,,,,,,
NYG,NaN,-3.511438,-4.601495,2.759891,11.519648,-2.958597,13.224958,6.829377,4.609181,3.274104,...,9.625618,-0.546579,12.061409,12.478149,16.410572,17.771036,18.077847,7.142601,17.083942,23.093407
NO,11.697819,NaN,-5.406795,1.954591,10.714348,-3.763897,12.419659,6.024077,3.803882,2.468804,...,8.820318,-1.351879,11.256109,11.672850,15.605272,16.965736,17.272547,6.337301,16.278641,22.288109
CIN,11.248383,-4.766174,NaN,1.505155,10.264912,-4.213333,11.970222,5.574641,3.354445,2.019368,...,8.370882,-1.801315,10.806673,11.223413,15.155836,16.516300,16.823111,5.887865,15.829206,21.838673
PIT,11.078232,-4.936325,-6.026381,NaN,10.094761,-4.383484,11.800072,5.404490,3.184295,1.849217,...,8.200731,-1.971466,10.636522,11.053263,14.985685,16.346149,16.652960,5.717714,15.659055,21.668522
TB,11.037378,-4.977179,-6.067235,1.294151,NaN,-4.424337,11.759218,5.363637,3.143441,1.808363,...,8.159878,-2.012320,10.595669,11.012409,14.944832,16.305296,16.612106,5.676861,15.618201,21.627666
DEN,9.813929,-6.200628,-7.290685,0.070701,8.830458,NaN,10.535769,4.140187,1.919991,0.584914,...,6.936428,-3.235769,9.372219,9.788960,13.721382,15.081846,15.388657,4.453411,14.394752,20.404217
WAS,10.003200,-6.011357,-7.101413,0.259973,9.019730,-5.458516,NaN,4.329459,2.109263,0.774185,...,7.125699,-3.046498,9.561491,9.978231,13.910653,15.271118,15.577929,4.642683,14.584023,20.593489
LV,9.269299,-6.745258,-7.835314,-0.473928,8.285829,-6.192417,9.991139,NaN,1.375362,0.040284,...,6.391798,-3.780399,8.827590,9.244330,13.176752,14.537216,14.844027,3.908782,13.850122,19.859589
CHI,9.057020,-6.957536,-8.047592,-0.686207,8.073550,-6.404695,9.778861,3.383279,NaN,-0.171994,...,6.179520,-3.992677,8.615312,9.032052,12.964474,14.324938,14.631748,3.696503,13.637844,19.647310
LAC,8.811684,-7.202873,-8.292930,-0.931544,7.828213,-6.650032,9.533524,3.137942,0.917747,NaN,...,5.934183,-4.238014,8.369974,8.786715,12.719137,14.079601,14.386412,3.451166,13.392507,19.401974
ATL,7.735157,-8.279400,-9.369456,-2.008070,6.751687,-7.726559,8.456997,2.061416,-0.158780,-1.493858,...,4.857656,-5.314541,7.293447,7.710188,11.642611,13.003075,13.309885,2.374640,12.315980,18.325447
PHI,6.958139,-9.056417,-10.146473,-2.785088,5.974669,-8.503576,7.679980,1.284399,-0.935797,-2.270875,...,4.080639,-6.091558,6.516431,6.933171,10.865593,12.226057,12.532867,1.597622,11.538963,17.548429
CLE,5.043348,-10.971209,-12.061265,-4.699879,4.059878,-10.418367,5.765189,-0.630393,-2.850589,-4.185667,...,2.165848,-8.006350,4.601639,5.018380,8.950802,10.311266,10.618076,-0.317169,9.624171,15.633637
IND,4.139206,-11.875350,-12.965406,-5.604021,3.155736,-11.322509,4.861047,-1.534535,-3.754730,-5.089808,...,1.261706,-8.910491,3.697497,4.114238,8.046659,9.407125,9.713935,-1.221311,8.720030,14.729496
CAR,3.861079,-12.153478,-13.243534,-5.882149,2.877608,-11.600636,4.582919,-1.812662,-4.032858,-5.367936,...,0.983578,-9.188619,3.419370,3.836110,7.768532,9.128997,9.435807,-1.499439,8.441902,14.451368
ARI,1.975724,-14.038833,-15.128889,-7.767504,0.992253,-13.485991,2.697564,-3.698018,-5.918213,-7.253291,...,-0.901777,-11.073974,1.534014,1.950755,5.883177,7.243641,7.550452,-3.384794,6.556547,12.566013
SF,1.984728,-14.029828,-15.119884,-7.758499,1.001258,-13.476987,2.706569,-3.689013,-5.909209,-7.244287,...,-0.892772,-11.064969,1.543019,1.959760,5.892181,7.252646,7.559456,-3.375789,6.565551,12.575018
MIA,0.574593,-15.439963,-16.530020,-9.168634,-0.408877,-14.887122,1.296434,-5.099148,-7.319344,-8.654421,...,-2.302907,-12.475104,0.132884,0.549625,4.482047,5.842511,6.149322,-4.785924,5.155416,11.164883
NYJ,0.255860,-15.758697,-16.848753,-9.487368,-0.727610,-15.205855,0.977700,-5.417881,-7.638077,-8.973155,...,-2.621641,-12.793838,-0.185849,0.230891,4.163313,5.523778,5.830588,-5.104657,4.836683,10.846149
DET,-0.669565,-16.684122,-17.774178,-10.412792,-1.653035,-16.131281,0.052276,-6.343306,-8.563501,-9.898580,...,-3.547065,-13.719263,-1.111274,-0.694533,3.237888,4.598353,4.905163,-6.030082,3.911258,9.920725
GB,-0.962465,-16.977022,-18.067078,-10.705692,-1.945935,-16.424181,-0.240624,-6.636206,-8.856401,-10.191480,...,-3.839966,-14.012163,-1.404174,-0.987433,2.944988,4.305453,4.612263,-6.322982,3.618358,9.627825
SEA,-1.636034,-17.650591,-18.740646,-11.379261,-2.619504,-17.097750,-0.914194,-7.309775,-9.529971,-10.865049,...,-4.513535,-14.685732,-2.077743,-1.661003,2.271419,3.631884,3.938694,-6.996552,2.944789,8.954255
HOU,-1.785475,-17.800032,-18.890087,-11.528702,-2.768945,-17.247190,-1.063634,-7.459216,-9.679412,-11.014490,...,NaN,-14.835173,-2.227184,-1.810443,2.121978,3.482443,3.789253,-7.145992,2.795348,8.804814
JAX,-2.386633,-18.401190,-19.491245,-12.129860,-3.370103,-17.848349,-1.664793,-8.060374,-10.280570,-11.615648,...,-5.264134,NaN,-2.828342,-2.411602,1.520820,2.881285,3.188095,-7.747150,2.194190,8.203656
LA,-5.575556,-21.590113,-22.680168,-15.318783,-6.559026,-21.037271,-4.853715,-11.249297,-13.469493,-14.804571,...,-8.453056,-18.625254,NaN,-5.600524,-1.668103,-0.307638,-0.000828,-10.936073,-0.994733,5.014733
NE,-5.761862,-21.776419,-22.866474,-15.505089,-6.745332,-21.223577,-5.040021,-11.435603,-13.655799,-14.990877,...,-8.639362,-18.811560,-6.203571,NaN,-1.854409,-0.493944,-0.187134,-11.122379,-1.181039,4.828427
KC,-5.964471,-21.979027,-23.069084,-15.707699,-6.947941,-21.426186,-5.242630,-11.638212,-13.858408,-15.193485,...,-8.841971,-19.014168,-6.406180,-5.989439,NaN,-0.696553,-0.389743,-11.324988,-1.383648,4.625818
TEN,-6.112143,-22.126699,-23.216755,-15.855370,-7.095613,-21.573858,-5.390302,-11.785884,-14.006080,-15.341158,...,-8.989643,-19.161840,-6.553852,-6.137111,-2.204690,NaN,-0.537415,-11.472660,-1.531320,4.478147
DAL,-6.244547,-22.259104,-23.349159,-15.987774,-7.228017,-21.706263,-5.522707,-11.918288,-14.138484,-15.473562,...,-9.122047,-19.294245,-6.686256,-6.269516,-2.337094,-0.976629,NaN,-11.605064,-1.663724,4.345742
MIN,-8.282949,-24.297506,-25.387562,-18.026176,-9.266420,-23.744665,-7.561109,-13.956691,-16.176888,-17.511965,...,-11.160450,-21.332647,-8.724659,-8.307919,-4.375496,-3.015032,-2.708221,NaN,-3.702127,2.307340
BAL,-9.525177,-25.539734,-26.629791,-19.268404,-10.508648,-24.986893,-8.803337,-15.198918,-17.419113,-18.754192,...,-12.402678,-22.574875,-9.966887,-9.550146,-5.617724,-4.257259,-3.950449,-14.885695,NaN,1.065112
BUF,-10.420507,-26.435064,-27.525120,-20.163734,-11.403978,-25.882223,-9.698668,-16.094250,-18.314445,-19.649523,...,-13.298008,-23.470205,-10.862217,-10.445477,-6.513054,-5.152590,-4.845779,-15.781025,-5.839684,NaN

In [16]:
df

team,CIN,NO,DEN,JAX,PIT,ARI,LAC,MIA,CHI,ATL,...,GB,LA,WAS,CAR,KC,BAL,TEN,DAL,DET,BUF
team,,,,,,,,,,,,,,,,,,,,,
CIN,NaN,5.283143,6.334793,19.911533,6.452428,14.372889,8.050846,16.614302,7.908303,9.100469,...,18.613106,22.879662,7.844983,13.870409,22.589159,27.305855,23.427835,23.630831,18.534031,26.997211
NO,3.701704,NaN,4.661129,18.237869,4.778764,12.699224,6.377182,14.940637,6.234639,7.426805,...,16.939442,21.205997,6.171319,12.196745,20.915495,25.632191,21.754171,21.957167,16.860367,25.323547
DEN,3.354952,3.262727,NaN,17.891117,4.432012,12.352472,6.030430,14.593884,5.887887,7.080052,...,16.592690,20.859245,5.824567,11.849993,20.568743,25.285439,21.407419,21.610415,16.513615,24.976795
JAX,1.712530,1.620305,2.671955,NaN,2.789590,10.710051,4.388008,12.951463,4.245465,5.437631,...,14.950268,19.216824,4.182145,10.207571,18.926321,23.643017,19.764997,19.967993,14.871194,23.334373
PIT,-0.921846,-1.014071,0.037578,13.614320,NaN,8.075674,1.753632,10.317086,1.611089,2.803254,...,12.315891,16.582447,1.547769,7.573194,16.291945,21.008640,17.130621,17.333616,12.236817,20.699997
ARI,-2.036967,-2.129192,-1.077542,12.499199,-0.959907,NaN,0.638511,9.201966,0.495968,1.688134,...,11.200770,15.467327,0.432648,6.458074,15.176825,19.893518,16.015501,16.218496,11.121696,19.584877
LAC,-2.351041,-2.443266,-1.391617,12.185125,-1.273982,6.646479,NaN,8.887892,0.181894,1.374059,...,10.886696,15.153252,0.118574,6.143999,14.862749,19.579445,15.701426,15.904421,10.807623,19.270803
MIA,-2.350912,-2.443137,-1.391488,12.185254,-1.273852,6.646608,0.324566,NaN,0.182023,1.374188,...,10.886826,15.153381,0.118703,6.144128,14.862879,19.579575,15.701555,15.904551,10.807752,19.270931
CHI,-3.535109,-3.627334,-2.575684,11.001058,-2.458049,5.462411,-0.859631,7.703824,NaN,0.189992,...,9.702629,13.969185,-1.065494,4.959932,13.678682,18.395378,14.517359,14.720354,9.623555,18.086735
ATL,-5.891132,-5.983357,-4.931707,8.645035,-4.814072,3.106388,-3.215654,5.347801,-3.358197,NaN,...,7.346605,11.613161,-3.421517,2.603909,11.322659,16.039354,12.161335,12.364330,7.267532,15.730713
NYJ,-6.054507,-6.146732,-5.095082,8.481659,-4.977447,2.943013,-3.379029,5.184426,-3.521572,-2.329406,...,7.183230,11.449787,-3.584892,2.440534,11.159285,15.875978,11.997961,12.200956,7.104157,15.567337
LV,-6.629638,-6.721863,-5.670213,7.906528,-5.552578,2.367882,-3.954160,4.609295,-4.096703,-2.904537,...,6.608099,10.874656,-4.160023,1.865403,10.584153,15.300848,11.422830,11.625825,6.529026,14.992207
MIN,-6.076764,-6.168989,-5.117339,8.459402,-4.999704,2.920757,-3.401286,5.162169,-3.543828,-2.351663,...,7.160974,11.427530,-3.607149,2.418277,11.137028,15.853722,11.975704,12.178699,7.081900,15.545080
PHI,-7.008299,-7.100524,-6.048875,7.527867,-5.931240,1.989221,-4.332821,4.230634,-4.475364,-3.283199,...,6.229438,10.495995,-4.538684,1.486741,10.205492,14.922187,11.044168,11.247164,6.150364,14.613545
SEA,-7.459701,-7.551926,-6.500276,7.076466,-6.382641,1.537820,-4.784223,3.779232,-4.926765,-3.734600,...,5.778037,10.044593,-4.990086,1.035340,9.754090,14.470785,10.592767,10.795762,5.698963,14.162144
SF,-7.689020,-7.781245,-6.729596,6.847146,-6.611960,1.308500,-5.013542,3.549912,-5.156085,-3.963920,...,5.548717,9.815273,-5.219405,0.806020,9.524771,14.241466,10.363447,10.566442,5.469644,13.932824
HOU,-7.597355,-7.689580,-6.637931,6.938811,-6.520296,1.400165,-4.921877,3.641577,-5.064420,-3.872255,...,5.640382,9.906939,-5.127740,0.897685,9.616436,14.333130,10.455112,10.658108,5.561308,14.024488
CLE,-8.895847,-8.988072,-7.936423,5.640319,-7.818788,0.101673,-6.220369,2.343086,-6.362912,-5.170747,...,4.341890,8.608446,-6.426232,-0.400807,8.317944,13.034638,9.156620,9.359615,4.262816,12.725997
TB,-10.317989,-10.410213,-9.358564,4.218177,-9.240929,-1.320469,-7.642511,0.920944,-7.785054,-6.592888,...,2.919748,7.186305,-7.848374,-1.822948,6.895802,11.612497,7.734478,7.937474,2.840675,11.303856
IND,-10.321996,-10.414221,-9.362572,4.214170,-9.244936,-1.324476,-7.646518,0.916937,-7.789061,-6.596895,...,2.915741,7.182298,-7.852381,-1.826955,6.891795,11.608490,7.730472,7.933467,2.836668,11.299849
NE,-10.004095,-10.096320,-9.044671,4.532071,-8.927035,-1.006575,-7.328618,1.234837,-7.471160,-6.278995,...,3.233642,7.500198,-7.534481,-1.509055,7.209695,11.926391,8.048372,8.251368,3.154568,11.617749
NYG,-11.033501,-11.125727,-10.074077,3.502665,-9.956442,-2.035981,-8.358023,0.205432,-8.500566,-7.308401,...,2.204236,6.470792,-8.563887,-2.538461,6.180290,10.896984,7.018966,7.221961,2.125163,10.588343
GB,-11.531599,-11.623825,-10.572175,3.004567,-10.454540,-2.534079,-8.856121,-0.292667,-8.998665,-7.806499,...,NaN,5.972694,-9.061985,-3.036559,5.682191,10.398886,6.520868,6.723863,1.627064,10.090244
LA,-12.075815,-12.168040,-11.116391,2.460351,-10.998755,-3.078295,-9.400337,-0.836883,-9.542880,-8.350715,...,1.161922,NaN,-9.606200,-3.580775,5.137976,9.854671,5.976652,6.179647,1.082848,9.546029
WAS,-12.578551,-12.670776,-11.619127,1.957615,-11.501492,-3.581031,-9.903073,-1.339618,-10.045616,-8.853451,...,0.659186,4.925742,NaN,-4.083511,4.635240,9.351934,5.473916,5.676911,0.580112,9.043293
CAR,-13.364179,-13.456404,-12.404755,1.171988,-12.287119,-4.366659,-10.688701,-2.125246,-10.831244,-9.639078,...,-0.126441,4.140115,-10.894564,NaN,3.849612,8.566307,4.688289,4.891284,-0.205515,8.257666
KC,-16.000601,-16.092827,-15.041176,-1.464435,-14.923541,-7.003081,-13.325123,-4.761668,-13.467666,-12.275500,...,-2.762864,1.503693,-13.530986,-7.505560,NaN,5.929885,2.051867,2.254862,-2.841937,5.621243
BAL,-16.655592,-16.747818,-15.696168,-2.119426,-15.578533,-7.658072,-13.980114,-5.416659,-14.122658,-12.930492,...,-3.417855,0.848701,-14.185978,-8.160552,0.558198,NaN,1.396875,1.599870,-3.496929,4.966252
TEN,-17.464355,-17.556581,-16.504932,-2.928190,-16.387297,-8.466836,-14.788878,-6.225424,-14.931421,-13.739256,...,-4.226619,0.039937,-14.994741,-8.969316,-0.250566,4.466129,NaN,0.791106,-4.305693,4.157488
DAL,-18.081791,-18.174015,-17.122366,-3.545625,-17.004730,-9.084270,-15.406313,-6.842858,-15.548856,-14.356690,...,-4.844054,-0.577497,-15.612176,-9.586750,-0.868000,3.848695,-0.029324,NaN,-4.923127,3.540053
DET,-18.875898,-18.968124,-17.916473,-4.339732,-17.798840,-9.878378,-16.200420,-7.636966,-16.342964,-15.150798,...,-5.638161,-1.371605,-16.406284,-10.380857,-1.662107,3.054587,-0.823431,-0.620436,NaN,2.745946
BUF,-21.118116,-21.210342,-20.158691,-6.581950,-20.041058,-12.120596,-18.442638,-9.879184,-18.585182,-17.393017,...,-7.880379,-3.613823,-18.648502,-12.623075,-3.904325,0.812369,-3.065649,-2.862654,-7.959453,NaN