In [8]:
import dgl
import lightning.pytorch as pl
import pandas as pd
import torch
from sportsml.mongo import client
from sportsml.nba.data.features import GRAPH_FEATURES
from sportsml.nba.data.nodes import team_abr_map
from sportsml.layers.gnn.encoder.heterogcn import HeteroGCNEncoder
from sportsml.layers.gnn.predictor.heteronn import HeteroNNPredictor
from sportsml.models.gnn import GraphModel
from sportsml.utils.datamodule import HeteroGraphDataModule
from sportsml.utils.heterograph import heterograph_encoder

In [9]:
games = pd.DataFrame(client.nba.games.find({})).dropna(subset=GRAPH_FEATURES)

In [10]:
games['won'] = games['PTS'] > games['PTS_OPP']
games['HOME'] = games['HOME'].astype(bool)
games['y'] = games['PTS'] - games['PTS_OPP']

In [11]:
dm = HeteroGraphDataModule(
    games=games,
    feature_columns=GRAPH_FEATURES,
    target_columns=['y'],
    win_column='won',
    home_column='HOME',
    season_column='SEASON',
    date_column='GAME_DATE',
    team_column='TEAM_ABBREVIATION',
    num_nodes=30,
    batch_size=16
)

In [12]:
model = GraphModel(
    encoder=HeteroGCNEncoder(len(GRAPH_FEATURES), 300),
    predictor=HeteroNNPredictor(300, 300, 1),
)

/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/parsing.py:197: UserWarning: Attribute 'encoder' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['encoder'])`.
  rank_zero_warn(
/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/parsing.py:197: UserWarning: Attribute 'predictor' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['predictor'])`.
  rank_zero_warn(

In [13]:
trainer = pl.Trainer(
    max_epochs=-1,
    logger=pl.loggers.CSVLogger(save_dir="model", name="model"),
    callbacks=[
        pl.callbacks.ModelCheckpoint(monitor="val_rmse"),
        pl.callbacks.early_stopping.EarlyStopping(monitor="val_rmse", patience=10)
    ]
)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

In [14]:
trainer.fit(model, dm)

  | Name            | Type                | Params
--------------------------------------------------------
0 | encoder         | HeteroGCNEncoder    | 562 K
1 | predictor       | HeteroNNPredictor   | 367 K
2 | rmse            | MeanSquaredError    | 0
3 | mae             | MeanAbsoluteError   | 0
4 | accuracy_score  | MulticlassAccuracy  | 0
5 | precision_score | MulticlassPrecision | 0
6 | recall_score    | MulticlassRecall    | 0
--------------------------------------------------------
929 K     Trainable params
0         Non-trainable params
929 K     Total params
3.719     Total estimated model params size (MB)

Epoch 1: 100%|██████████| 274/274 [04:53<00:00,  1.07s/it, v_num=3, train_loss=82.00, val_rmse=13.30]

/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:152: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)

Epoch 14: 100%|██████████| 274/274 [06:02<00:00,  1.32s/it, v_num=3, train_loss=85.00, val_rmse=12.90]

In [15]:
trainer.test(model, dm)

Testing DataLoader 0: 100%|██████████| 35/35 [00:18<00:00,  1.90it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   Runningstage.testing    ┃                           ┃
┃          metric           ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│       test_accuracy       │    0.6538461446762085     │
│         test_mae          │     9.948995590209961     │
│      test_precision       │    0.6538611650466919     │
│        test_recall        │    0.6538461446762085     │
│         test_rmse         │    12.632049560546875     │
└───────────────────────────┴───────────────────────────┘

[{'test_rmse': 12.632049560546875,
  'test_mae': 9.948995590209961,
  'test_accuracy': 0.6538461446762085,
  'test_precision': 0.6538611650466919,
  'test_recall': 0.6538461446762085}]

In [25]:
s2022 = games[games['SEASON'] == 2022]

In [27]:
g = heterograph_encoder(
    src=s2022['src'].values,
    dst=s2022['target'].values,
    feat=s2022[GRAPH_FEATURES].values,
    won_mask=s2022['won'].values,
    num_nodes=30
)

In [28]:
preds = model.predict(g)

In [40]:
hu, hv = preds.edges(etype="home")
df_home = pd.DataFrame()
df_home['team'] = hv
df_home['opp'] = hu
df_home['f'] = preds.edges["home"].data["pred"].detach().numpy()
df_home = df_home.pivot_table(index="team", columns="opp", values="f")
df_home = df_home.rename(index=team_abr_map, columns=team_abr_map)
df_home = df_home.reindex(df.mean(axis=1).sort_values(ascending=False).index)
df_home = df_home.reindex(df.mean(axis=1).sort_values(ascending=False).index, axis=1)

In [42]:
hu, hv = preds.edges(etype="away")
df_away = pd.DataFrame()
df_away['team'] = hv
df_away['opp'] = hu
df_away['f'] = preds.edges["away"].data["pred"].detach().numpy()
df_away = df_away.pivot_table(index="team", columns="opp", values="f")
df_away = df_away.rename(index=team_abr_map, columns=team_abr_map)
df_away = df_away.reindex(df.mean(axis=1).sort_values(ascending=False).index)
df_away = df_away.reindex(df.mean(axis=1).sort_values(ascending=False).index, axis=1)

In [41]:
df_home

team,CHH,SAS,HOU,DET,ORL,MEM,IND,WAS,POR,UTA,...,CLE,PHX,MIL,GSW,LAC,ATL,SAC,DEN,PHI,BOS
team,,,,,,,,,,,,,,,,,,,,,
CHH,NaN,-1.145913,-5.273188,-5.654452,-5.874982,-5.793666,-6.844969,-7.429021,-7.719773,-7.854171,...,-13.635729,-13.971751,-14.127132,-14.061489,-14.586994,-15.558295,-15.736526,-15.808868,-17.292986,-19.510120
SAS,5.041778,NaN,-0.916425,-1.297690,-1.518219,-1.436904,-2.488206,-3.072258,-3.363011,-3.497409,...,-9.278966,-9.614988,-9.770370,-9.704727,-10.230232,-11.201532,-11.379763,-11.452106,-12.936223,-15.153357
HOU,6.855463,5.024534,NaN,0.515995,0.295465,0.376781,-0.674521,-1.258574,-1.549326,-1.683724,...,-7.465281,-7.801304,-7.956685,-7.891042,-8.416548,-9.387848,-9.566078,-9.638421,-11.122538,-13.339672
DET,7.915401,6.084473,1.957198,NaN,1.355404,1.436719,0.385417,-0.198635,-0.489388,-0.623785,...,-6.405343,-6.741365,-6.896747,-6.831103,-7.356609,-8.327909,-8.506140,-8.578483,-10.062599,-12.279734
ORL,6.776845,4.945916,0.818642,0.437377,NaN,0.298163,-0.753139,-1.337192,-1.627944,-1.762342,...,-7.543899,-7.879922,-8.035303,-7.969660,-8.495165,-9.466466,-9.644696,-9.717039,-11.201157,-13.418290
MEM,12.123260,10.292332,6.165057,5.783792,5.563263,NaN,4.593276,4.009224,3.718472,3.584074,...,-2.197484,-2.533506,-2.688888,-2.623244,-3.148750,-4.120050,-4.298280,-4.370624,-5.854741,-8.071875
IND,12.091353,10.260425,6.133150,5.751885,5.531356,5.612671,NaN,3.977317,3.686564,3.552166,...,-2.229391,-2.565413,-2.720795,-2.655152,-3.180657,-4.151958,-4.330188,-4.402531,-5.886648,-8.103782
WAS,11.327474,9.496545,5.369270,4.988006,4.767476,4.848792,3.797489,NaN,2.922685,2.788287,...,-2.993270,-3.329293,-3.484674,-3.419031,-3.944537,-4.915837,-5.094068,-5.166410,-6.650527,-8.867661
POR,7.753939,5.923010,1.795736,1.414471,1.193942,1.275257,0.223955,-0.360097,NaN,-0.785248,...,-6.566805,-6.902828,-7.058209,-6.992566,-7.518071,-8.489371,-8.667602,-8.739945,-10.224062,-12.441196
UTA,11.133331,9.302402,5.175128,4.793863,4.573333,4.654649,3.603346,3.019294,2.728542,NaN,...,-3.187413,-3.523436,-3.678817,-3.613174,-4.138680,-5.109980,-5.288210,-5.360554,-6.844670,-9.061804
NOK,10.159419,8.328490,4.201216,3.819951,3.599422,3.680737,2.629435,2.045383,1.754630,1.620232,...,-4.161325,-4.497347,-4.652729,-4.587086,-5.112591,-6.083891,-6.262122,-6.334465,-7.818582,-10.035716
CHI,13.298163,11.467235,7.339960,6.958695,6.738166,6.819482,5.768179,5.184127,4.893374,4.758977,...,-1.022581,-1.358603,-1.513984,-1.448341,-1.973847,-2.945147,-3.123377,-3.195721,-4.679837,-6.896972
TOR,15.329269,13.498341,9.371067,8.989801,8.769272,8.850588,7.799285,7.215233,6.924481,6.790083,...,1.008526,0.672503,0.517122,0.582765,0.057260,-0.914041,-1.092271,-1.164614,-2.648731,-4.865865
SEA,14.220064,12.389135,8.261861,7.880596,7.660067,7.741383,6.690080,6.106028,5.815275,5.680878,...,-0.100680,-0.436702,-0.592084,-0.526441,-1.051946,-2.023246,-2.201477,-2.273820,-3.757937,-5.975071
MIA,15.977730,14.146801,10.019527,9.638262,9.417732,9.499048,8.447746,7.863694,7.572941,7.438543,...,1.656986,1.320964,1.165582,1.231225,0.705720,-0.265580,-0.443811,-0.516154,-2.000271,-4.217405
NYK,14.806986,12.976057,8.848783,8.467518,8.246988,8.328304,7.277001,6.692949,6.402197,6.267799,...,0.486242,0.150219,-0.005162,0.060481,-0.465024,-1.436325,-1.614555,-1.686898,-3.171015,-5.388149
DAL,13.530918,11.699989,7.572715,7.191450,6.970921,7.052237,6.000934,5.416882,5.126129,4.991732,...,-0.789826,-1.125848,-1.281230,-1.215587,-1.741092,-2.712392,-2.890623,-2.962966,-4.447083,-6.664217
LAL,16.088379,14.257450,10.130176,9.748911,9.528381,9.609697,8.558394,7.974342,7.683590,7.549192,...,1.767635,1.431612,1.276231,1.341874,0.816369,-0.154932,-0.333162,-0.405505,-1.889622,-4.106756
NJN,16.088947,14.258018,10.130743,9.749479,9.528950,9.610265,8.558962,7.974910,7.684158,7.549760,...,1.768203,1.432180,1.276799,1.342442,0.816936,-0.154364,-0.332594,-0.404938,-1.889054,-4.106188
MIN,15.822912,13.991983,9.864709,9.483444,9.262915,9.344231,8.292928,7.708876,7.418123,7.283725,...,1.502168,1.166145,1.010764,1.076407,0.550902,-0.420398,-0.598629,-0.670972,-2.155089,-4.372223
CLE,22.162428,20.331499,16.204224,15.822960,15.602430,15.683746,14.632443,14.048391,13.757639,13.623241,...,NaN,7.505661,7.350280,7.415923,6.890418,5.919117,5.740887,5.668544,4.184427,1.967293
PHX,17.649147,15.818218,11.690945,11.309679,11.089149,11.170465,10.119164,9.535110,9.244358,9.109961,...,3.328403,NaN,2.836999,2.902642,2.377137,1.405837,1.227607,1.155263,-0.328854,-2.545988
MIL,17.994202,16.163273,12.035997,11.654734,11.434204,11.515519,10.464216,9.880165,9.589413,9.455014,...,3.673457,3.337434,NaN,3.247696,2.722191,1.750890,1.572660,1.500317,0.016200,-2.200934
GSW,19.904526,18.073597,13.946321,13.565057,13.344527,13.425842,12.374540,11.790488,11.499736,11.365337,...,5.583781,5.247758,5.092377,NaN,4.632514,3.661214,3.482984,3.410640,1.926524,-0.290610
LAC,19.232407,17.401478,13.274203,12.892939,12.672409,12.753725,11.702422,11.118370,10.827618,10.693220,...,4.911663,4.575640,4.420259,4.485902,NaN,2.989096,2.810866,2.738522,1.254405,-0.962729
ATL,17.751133,15.920205,11.792931,11.411666,11.191136,11.272451,10.221149,9.637097,9.346345,9.211946,...,3.430390,3.094367,2.938986,3.004629,2.479124,NaN,1.329593,1.257250,-0.226867,-2.444001
SAC,16.859905,15.028976,10.901702,10.520437,10.299908,10.381224,9.329921,8.745869,8.455116,8.320719,...,2.539161,2.203138,2.047757,2.113400,1.587895,0.616595,NaN,0.366021,-1.118096,-3.335230
DEN,19.546139,17.715210,13.587934,13.206670,12.986140,13.067455,12.016153,11.432101,11.141349,11.006950,...,5.225394,4.889371,4.733990,4.799633,4.274127,3.302827,3.124597,NaN,1.568137,-0.648997
PHI,19.987949,18.157021,14.029746,13.648481,13.427952,13.509268,12.457965,11.873913,11.583160,11.448763,...,5.667205,5.331182,5.175801,5.241445,4.715939,3.744639,3.566408,3.494065,NaN,-0.207186
BOS,23.863544,22.032616,17.905342,17.524076,17.303547,17.384863,16.333561,15.749508,15.458755,15.324358,...,9.542800,9.206778,9.051396,9.117040,8.591534,7.620234,7.442003,7.369660,5.885543,NaN

In [43]:
df_away

team,CHH,SAS,HOU,DET,ORL,MEM,IND,WAS,POR,UTA,...,CLE,PHX,MIL,GSW,LAC,ATL,SAC,DEN,PHI,BOS
team,,,,,,,,,,,,,,,,,,,,,
CHH,NaN,-5.877817,-9.079470,-8.996667,-8.072197,-13.625116,-13.535639,-12.343637,-9.206455,-12.686680,...,-24.443541,-18.999535,-19.870552,-21.780590,-20.957569,-19.390284,-18.346127,-21.148642,-21.029884,-25.518127
SAS,-0.406074,NaN,-6.366401,-6.283598,-5.359128,-10.912047,-10.822570,-9.630569,-6.493387,-9.973611,...,-21.730473,-16.286465,-17.157482,-19.067520,-18.244499,-16.677214,-15.633057,-18.435574,-18.316814,-22.805058
HOU,4.789371,2.030696,NaN,-1.088154,-0.163683,-5.716603,-5.627126,-4.435124,-1.297943,-4.778167,...,-16.535027,-11.091021,-11.962038,-13.872077,-13.049055,-11.481770,-10.437613,-13.240129,-13.121370,-17.609613
DET,4.918869,2.160195,-1.041458,NaN,-0.034184,-5.587104,-5.497627,-4.305626,-1.168444,-4.648667,...,-16.405529,-10.961521,-11.832540,-13.742579,-12.919556,-11.352271,-10.308113,-13.110630,-12.991872,-17.480114
ORL,5.036173,2.277498,-0.924154,-0.841352,NaN,-5.469800,-5.380323,-4.188322,-1.051140,-4.531364,...,-16.288225,-10.844218,-11.715237,-13.625275,-12.802253,-11.234968,-10.190810,-12.993326,-12.874569,-17.362812
MEM,4.983250,2.224575,-0.977077,-0.894275,0.030196,NaN,-5.433247,-4.241245,-1.104064,-4.584288,...,-16.341148,-10.897141,-11.768160,-13.678198,-12.855176,-11.287891,-10.243733,-13.046249,-12.927492,-17.415733
IND,5.816792,3.058117,-0.143535,-0.060732,0.863738,-4.689181,NaN,-3.407703,-0.270521,-3.750745,...,-15.507607,-10.063599,-10.934617,-12.844656,-12.021633,-10.454349,-9.410191,-12.212708,-12.093949,-16.582191
WAS,6.280129,3.521455,0.319802,0.402605,1.327075,-4.225844,-4.136367,NaN,0.192816,-3.287408,...,-15.044269,-9.600262,-10.471279,-12.381318,-11.558296,-9.991011,-8.946854,-11.749371,-11.630611,-16.118855
POR,6.683340,3.924665,0.723012,0.805815,1.730286,-3.822634,-3.733156,-2.541156,NaN,-2.884197,...,-14.641058,-9.197052,-10.068069,-11.978107,-11.155087,-9.587801,-8.543644,-11.346160,-11.227402,-15.715645
UTA,7.220196,4.461522,1.259869,1.342672,2.267142,-3.285777,-3.196300,-2.004299,1.132883,NaN,...,-14.104202,-8.660194,-9.531213,-11.441252,-10.618229,-9.050944,-8.006786,-10.809303,-10.690545,-15.178787
NOK,6.997455,4.238780,1.037127,1.119930,2.044401,-3.508519,-3.419041,-2.227041,0.910141,-2.570082,...,-14.326943,-8.882936,-9.753954,-11.663993,-10.840971,-9.273685,-8.229528,-11.032045,-10.913286,-15.401529
CHI,7.664436,4.905762,1.704109,1.786912,2.711382,-2.841537,-2.752060,-1.560059,1.577123,-1.903101,...,-13.659962,-8.215955,-9.086973,-10.997011,-10.173989,-8.606705,-7.562547,-10.365063,-10.246305,-14.734548
TOR,10.219250,7.460575,4.258922,4.341725,5.266195,-0.286724,-0.197247,0.994754,4.131936,0.651712,...,-11.105148,-5.661142,-6.532160,-8.442198,-7.619176,-6.051891,-5.007734,-7.810250,-7.691492,-12.179734
SEA,10.263525,7.504850,4.303197,4.386000,5.310471,-0.242449,-0.152972,1.039029,4.176211,0.695987,...,-11.060873,-5.616867,-6.487885,-8.397923,-7.574901,-6.007616,-4.963459,-7.765975,-7.647217,-12.135460
MIA,10.212201,7.453526,4.251874,4.334677,5.259147,-0.293772,-0.204295,0.987706,4.124888,0.644664,...,-11.112197,-5.668190,-6.539208,-8.449246,-7.626225,-6.058939,-5.014782,-7.817298,-7.698540,-12.186783
NYK,11.314920,8.556246,5.354593,5.437396,6.361866,0.808947,0.898424,2.090425,5.227607,1.747383,...,-10.009478,-4.565471,-5.436489,-7.346527,-6.523505,-4.956220,-3.912063,-6.714579,-6.595821,-11.084064
DAL,11.610578,8.851903,5.650251,5.733054,6.657524,1.104604,1.194082,2.386083,5.523265,2.043041,...,-9.713820,-4.269813,-5.140831,-7.050869,-6.227848,-4.660563,-3.616405,-6.418921,-6.300163,-10.788406
LAL,11.358976,8.600302,5.398649,5.481452,6.405922,0.853002,0.942480,2.134481,5.271663,1.791439,...,-9.965422,-4.521415,-5.392433,-7.302472,-6.479450,-4.912165,-3.868007,-6.670524,-6.551765,-11.040008
NJN,12.741533,9.982859,6.781206,6.864008,7.788479,2.235559,2.325037,3.517038,6.654220,3.173996,...,-8.582865,-3.138858,-4.009876,-5.919915,-5.096893,-3.529608,-2.485450,-5.287967,-5.169209,-9.657452
MIN,13.094591,10.335917,7.134264,7.217067,8.141538,2.588618,2.678095,3.870096,7.007278,3.527054,...,-8.229807,-2.785800,-3.656817,-5.566856,-4.743834,-3.176549,-2.132391,-4.934908,-4.816150,-9.304393
CLE,11.941154,9.182480,5.980827,6.063630,6.988101,1.435181,1.524658,2.716659,5.853841,2.373617,...,NaN,-3.939237,-4.810255,-6.720293,-5.897271,-4.329986,-3.285829,-6.088345,-5.969587,-10.457829
PHX,13.134388,10.375713,7.174061,7.256864,8.181334,2.628415,2.717892,3.909893,7.047075,3.566851,...,-8.190010,NaN,-3.617021,-5.527059,-4.704037,-3.136752,-2.092595,-4.895111,-4.776353,-9.264596
MIL,13.547805,10.789130,7.587478,7.670280,8.594750,3.041831,3.131309,4.323309,7.460491,3.980268,...,-7.776593,-2.332587,NaN,-5.113643,-4.290621,-2.723336,-1.679178,-4.481695,-4.362937,-8.851179
GSW,13.646512,10.887837,7.686185,7.768988,8.693459,3.140539,3.230016,4.422017,7.559199,4.078975,...,-7.677886,-2.233879,-3.104897,NaN,-4.191914,-2.624628,-1.580471,-4.382987,-4.264229,-8.752472
LAC,13.322442,10.563767,7.362115,7.444918,8.369389,2.816469,2.905946,4.097947,7.235129,3.754905,...,-8.001956,-2.557949,-3.428967,-5.339005,NaN,-2.948698,-1.904541,-4.707057,-4.588299,-9.076542
ATL,14.484639,11.725965,8.524312,8.607115,9.531586,3.978666,4.068143,5.260144,8.397326,4.917102,...,-6.839759,-1.395752,-2.266770,-4.176808,-3.353786,NaN,-0.742344,-3.544860,-3.426102,-7.914345
SAC,15.327721,12.569046,9.367393,9.450196,10.374666,4.821747,4.911224,6.103226,9.240408,5.760183,...,-5.996677,-0.552670,-1.423688,-3.333727,-2.510705,-0.943420,NaN,-2.701779,-2.583021,-7.071263
DEN,14.945559,12.186884,8.985231,9.068035,9.992505,4.439586,4.529063,5.721064,8.858246,5.378022,...,-6.378839,-0.934832,-1.805850,-3.715889,-2.892867,-1.325582,-0.281424,NaN,-2.965182,-7.453425
PHI,17.521179,14.762504,11.560851,11.643654,12.568125,7.015205,7.104682,8.296683,11.433865,7.953641,...,-3.803220,1.640787,0.769769,-1.140269,-0.317247,1.250038,2.294195,-0.508321,NaN,-4.877806
BOS,18.683672,15.924997,12.723345,12.806148,13.730618,8.177698,8.267176,9.459177,12.596359,9.116135,...,-2.640726,2.803281,1.932263,0.022224,0.845246,2.412531,3.456689,0.654172,0.772931,NaN